version: '3.8'

services:
  api:
    command: npm run dev
    volumes:
      - ./api/src:/usr/src/app/src
  frontend:
    command: npm run start
    volumes:
      - ./frontend:/frontend:delegated
      - /node_modules